import type { Internship } from "./types";

export const STORAGE_KEY = "interntrack.internships.v1";

export const seedInternships: Internship[] = [
  {
    id: "google-swe-intern",
    company: "Google",
    role: "Software Engineering Intern",
    url: "https://careers.google.com/jobs/results/software-engineering-intern",
    location: "Bangkok / Remote",
    deadline: "2026-09-27",
    status: "preparing",
    notes: "Focus on coding interviews and a concise resume tailored to Google.",
    documents: [
      { id: "g-resume", name: "Resume", completed: true },
      { id: "g-transcript", name: "Transcript", completed: false },
      { id: "g-portfolio", name: "Portfolio", completed: false },
      { id: "g-cover", name: "Cover Letter", completed: true },
    ],
    createdAt: "2026-09-10T09:00:00.000Z",
    priority: "high",
    tags: ["FAANG", "Software", "Remote"],
  },
  {
    id: "agoda-dev-intern",
    company: "Agoda",
    role: "Software Developer Intern",
    url: "https://careers.agoda.com/jobs/software-developer-intern",
    location: "Bangkok, Thailand",
    deadline: "2026-10-04",
    status: "saved",
    notes: "Review backend case studies and company product notes.",
    documents: [
      { id: "a-resume", name: "Resume", completed: true },
      { id: "a-transcript", name: "Transcript", completed: true },
      { id: "a-portfolio", name: "Portfolio", completed: false },
      { id: "a-cover", name: "Cover Letter", completed: false },
    ],
    createdAt: "2026-09-14T11:30:00.000Z",
    priority: "medium",
    tags: ["Travel", "Bangkok", "Backend"],
  },
  {
    id: "microsoft-swe-intern",
    company: "Microsoft",
    role: "Software Engineering Intern",
    url: "https://careers.microsoft.com/us/en/job/software-engineering-intern",
    location: "Singapore / Hybrid",
    deadline: "2026-10-12",
    status: "interview",
    notes: "Prepare system design stories and Azure project talking points.",
    documents: [
      { id: "m-resume", name: "Resume", completed: true },
      { id: "m-transcript", name: "Transcript", completed: true },
      { id: "m-portfolio", name: "Portfolio", completed: true },
      { id: "m-cover", name: "Cover Letter", completed: true },
    ],
    createdAt: "2026-09-02T08:15:00.000Z",
    priority: "high",
    tags: ["Cloud", "Interview"],
    applicationDate: "2026-09-05",
    followUpDate: "2026-09-12",
    interviewDate: "2026-09-28",
    interviewTime: "14:00",
    interviewLink: "https://teams.microsoft.com/l/meetup-join/demo",
    preparationNotes: "Review C#/TypeScript projects and behavioral STAR stories.",
  },
  {
    id: "shopee-product-intern",
    company: "Shopee",
    role: "Product Management Intern",
    url: "https://careers.shopee.com/job/product-management-intern",
    location: "Bangkok, Thailand",
    deadline: "2026-10-20",
    status: "applied",
    notes: "Submitted application with a product teardown of Shopee Live.",
    documents: [
      { id: "s-resume", name: "Resume", completed: true },
      { id: "s-transcript", name: "Transcript", completed: true },
      { id: "s-portfolio", name: "Portfolio", completed: true },
      { id: "s-cover", name: "Cover Letter", completed: false },
    ],
    createdAt: "2026-09-16T15:45:00.000Z",
    priority: "medium",
    tags: ["Product", "E-commerce"],
    applicationDate: "2026-09-18",
    followUpDate: "2026-09-25",
  },
  {
    id: "grab-frontend-intern",
    company: "Grab",
    role: "Frontend Engineering Intern",
    url: "https://www.grab.careers/jobs/frontend-engineering-intern",
    location: "Remote, Southeast Asia",
    deadline: "2026-09-18",
    status: "preparing",
    notes: "Deadline passed — decide whether to still submit or archive.",
    documents: [
      { id: "gr-resume", name: "Resume", completed: true },
      { id: "gr-transcript", name: "Transcript", completed: false },
      { id: "gr-portfolio", name: "Portfolio", completed: false },
      { id: "gr-cover", name: "Cover Letter", completed: false },
    ],
    createdAt: "2026-09-01T10:00:00.000Z",
    priority: "high",
    tags: ["Frontend", "Overdue"],
  },
  {
    id: "line-man-data-intern",
    company: "LINE MAN Wongnai",
    role: "Data Analyst Intern",
    url: "https://careers.linemanwongnai.com/data-analyst-intern",
    location: "Bangkok, Thailand",
    deadline: "2026-11-02",
    status: "saved",
    notes: "Need SQL practice set and a one-page analytics case study.",
    documents: [
      { id: "l-resume", name: "Resume", completed: false },
      { id: "l-transcript", name: "Transcript", completed: false },
      { id: "l-portfolio", name: "Portfolio", completed: false },
      { id: "l-cover", name: "Cover Letter", completed: false },
    ],
    createdAt: "2026-09-19T13:20:00.000Z",
    priority: "low",
    tags: ["Data", "Local"],
  },
];
